### ISSUE TITLE
limit projected ED50s to 2 digits

### ISSUE THREAD

**Issue by reefgenomics** [reefgenomics/CBASSED50#4]
hey Yulia, I thought this was fixed in a previous release? ED50 values should be limited to 2 digits after period = XY.ZZ °C

**Comment by greenjune-ship-it** [comment]
Hi @reefgenomics 

The following [line](https://github.com/greenjune-ship-it/CBASSED50/blob/abe9126eadc25fb183899a4d3f7c153459b4b39b/R/run-ed50-analysis.R#L111) of the code already does this. It exists in our previous release.

Probably you have to rerun the package installation to get the newest version of the R package from GitHub:

```
if(!require(devtools)){
   install.packages("devtools")
}

devtools::install_github("greenjune-ship-it/CBASSED50")
```
Please, let me know if it helps
